### PR TITLE
Add SPARQL query for extracting Urdu adjectives (#242)

### PR DESCRIPTION
**Pull request by Ekikereabasi-Nk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
This pull request introduces a new SPARQL query designed to retrieve Urdu adjectives and their grammatical forms from Wikidata. The query is inspired by the SPARQL code from the "Expand Scribe-Data Hindi verb queries" by KesharwaniArpita, and it aims to enhance our understanding and representation of Urdu lexicographical data.

Key features of the query:

1. Fetches the adjective's lemma (base form) from Wikidata.
2. Retrieves various grammatical forms associated with each adjective.
3. Filters results to include only forms where the language is set to "ur" (Urdu).
4. Displays the lexeme ID, lemma, and optional grammatical features for each result.

Context and significance:

-  This query is part of a broader effort to document and analyze Hindustani (Q11051), also known as Hindi-Urdu, a language spoken widely in India and Pakistan.

- While this specific query focuses on Urdu adjectives, it complements existing work on Hindi verbs, reflecting the close relationship between Hindi and Urdu within the Hindustani language complex.

The SPARQL query has been validated using the [Wikidata Query Service](https://query.wikidata.org/)
-->

### Related issue

- Related to #242

### CODE REVIEW

**Review by KesharwaniArpita — COMMENTED** [review]
@Ekikereabasi-Nk  You may want to check out the following QID for your grammatical feature:
Singulative Numeral: Q110786
Collective Numeral: Q146786
Oblique Case: Q1233197

**Comment by Ekikereabasi-Nk** [comment]
@KesharwaniArpita Thank you very much for the information. I will look at it

**Review by Ekikereabasi-Nk — COMMENTED** [review]
Hi @andrewtavis the files have been restored to their original state as requested. All unnecessary file/folder have been removed, ensuring the pull request only includes the intended work.

**Comment by andrewtavis** [comment]
I did a couple of minor edits here, @Ekikereabasi-Nk, but looking at some of the data it seems like there are many forms that we could still include or also make more specific by adding more properties to each form. Do you want to expand the current query and then we'll be good to merge? 😊

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis thanks for review and providing feedback. I appreciate your suggestion to expand the current query by including more forms and adding more properties to each form. I'm open to expanding the query as you've suggested

**Comment by andrewtavis** [comment]
Sounds great, @Ekikereabasi-Nk! Looking forward to the further commits! 😊

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I have worked on expanding, and updated the queries for urdu adjectives. Please take a look. Thank you

**Review by andrewtavis — APPROVED** [review]
As with the other ones, we need to combine the properties to get individual forms. Let's work towards doing this in future queries, @Ekikereabasi-Nk 😊 Thanks so much for the efforts here!

**Pull request merged**
