### PR TITLE
Danish nouns

### LINKED ISSUE #285: The current Danish query for nouns results in a timeout error
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

As shown in the attached Image this [query](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Danish/nouns/query_nouns.sparql) results in a timeout error 
a

### PR DESCRIPTION
**Pull request by OmarAI2003**
### Contributor checklist

- [x]This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

This PR refactors the SPARQL query by splitting it into separate eight files for each variable to resolve runtime issues. The original single-file implementation was leading to runtime problems. Adding the Non-Genitive Form to the JSON file To git red of erros by check_query_forms. 

### Related issue
-  Fixes  #285

Exuse me some for the MARKS and the spacing this was really erronous task.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Do we need these queries split up as much as they are, @OmarAI2003?

**Comment by OmarAI2003** [comment]
> Do we need these queries split up as much as they are, @OmarAI2003?

Well, previously, when I tried to group different combinations of two forms, I had a timeout error. Now I don’t think we need to make all those splits. I checked again and will make the necessary edits.

**Comment by andrewtavis** [comment]
I think it's honestly fine, @OmarAI2003 :) Just checking.

**Comment by OmarAI2003** [comment]
@andrewtavis  Now everything should be perfect, except there are duplicate entries per lexeme ID. That's because the actual forms on Wikidata are duplicated. For example, the same eight forms I got in this PR are in 16 forms for [this example](https://www.wikidata.org/wiki/Lexeme:L54603).The variable names  in the files are different from Wikidata that's to pass the checks.

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @OmarAI2003! Great to have Danish all finished up :)

**Pull request merged**
