### PR TITLE
Create query_adverbs.sparql

### PR DESCRIPTION
**Pull request by Otom-obhazi**
for adverb

### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Review by andrewtavis — APPROVED** [review]
No further edits are needed on this one here, @Otom-obhazi :) Well done!

**Comment by Otom-obhazi** [comment]
thank you.... any more task to do

**Comment by Otom-obhazi** [comment]
please can you check this out and give me feedback.

https://github.com/scribe-org/Scribe-Data/pull/368
https://github.com/scribe-org/Scribe-Data/pull/366
https://github.com/scribe-org/Scribe-Data/pull/365
https://github.com/scribe-org/Scribe-Data/pull/364

**Comment by andrewtavis** [comment]
Thanks for this @Otom-obhazi. Let me stress here as well, please make sure to get all of the forms when you're making the queries as that's a more full contribution to the project. If we need to go back and edit the queries afterwards, then it's adding more work potentially.

**Comment by Otom-obhazi** [comment]
@andrewtavis please what forms??

**Comment by andrewtavis** [comment]
In one of your adverb queries put ?lexeme as the first thing returned and you'll see a list of Wikidata item URIs - at least if the query returns things. With these queries we also want the forms of the word, which you can see by clicking on the URI and going to the item's page. When there scroll to the bottom for the forms. Not every one of the languages is going to have distinct forms for adverbs, but some might. Forms are things like the conjugations of a verb or the plural of a noun. Not only do we want to return the word itself, but we also want to return its forms - i.e. all the other data about the word.

Investigate some of the larger queries and investigate the URIs via returning ?lexeme from the query as well. Then you can check your queries and make sure that the forms are included. Specifically for Slovak there are forms that weren't included :) Try to make a new version of that one that functions like the other, larger queries.

**Comment by Otom-obhazi** [comment]
what do you mean when you say "forms when making the queries"

sorry, I'm a bit new to this, I'm usually a fast learner but this is a bit
comfusing

**Comment by andrewtavis** [comment]
Forms are just a way of talking about data on an item in Wikidata. If the item is a verb, then a form is a conjugation or something like this, whereas if it's a noun it could be its plural or gender.

**Comment by Otom-obhazi** [comment]
okay.. thank you

**Comment by Otom-obhazi** [comment]
can you assign any other contribution, because you corrected my mistakes.

**Comment by andrewtavis** [comment]
Feel free to look into queries in the newly opened issues :)

**Comment by andrewtavis** [comment]
Write in then and I can assign, and let us know which queries you want to work on 😊

**Pull request merged**
