### PR TITLE
Added type hints

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
Last time, I saw there were some missing type hints in the `utils.py` file. I just added the rest of them and used `Any` if it was not clear what will be returned 😄.

### Related issue

- #No related issue

### CODE REVIEW

**Comment by to-sta** [comment]
Starting from Python 3.9, built-in collection types can be used directly as generics. Since Python 3.9 is used I convert to the built-in `list` type.

**Comment by andrewtavis** [comment]
@to-sta, 0c87380 was valid to do given your comment [here](https://github.com/scribe-org/Scribe-Data/pull/181#issuecomment-2254477248), correct? I tool out all type imports of `List` and `Dict` and just used the built-ins instead :)

**Comment by to-sta** [comment]
Yeah, that is correct 👌🏻. Here are the [release notes](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections), in case you want to read more about.

**Review by andrewtavis — APPROVED** [review]
Nice, thanks for the confirmation and for some further great help to the project, @to-sta! 🚀 Great to have your influence here 😊

**Pull request merged**
