### PR TITLE
Expand polish verbs query 233

### PR DESCRIPTION
**Pull request by Ekikereabasi-Nk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

 ###Description

This pull request expands the Polish verbs functionality within Scribe-Data  by adding two new SPARQL query files designed to retrieve Polish verbs and their grammatical forms from Wikidata.

#### Changes Made:

1. **Renamed Query File**: 
   - The existing file `query_verbs.sparql` has been renamed to `query_verbs_1.sparql`. 
   
2. **New SPARQL Queries**: 
   - **`query_verbs_1.sparql`**: This query retrieves Polish verbs and their common grammatical forms such as infinitive, imperative, indicative, and various tenses (past, future).
   - **`query_verbs_2.sparql`**: This query is designed to retrieve Polish verbs with extended grammatical forms, including feminine, masculine, and neuter variations, as well as participles and aspectual distinctions (imperfective and perfective).

#### Testing
Both queries were tested using the [Wikidata Query Service](https://query.wikidata.org/). 

### Related issue

- #233

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @Ekikereabasi-Nk 👋 Would you be able to clean up the PR a little bit?

I'm seeing a couple of things on first glance:
- There are more English verbs being added to `scribe_data_json_export`, which we don't need in this PR
- There's also changes to the Urdu directory from your other PR, which would be great to remove from this one
- Can we also revert the changes to the load/update_files/total_data.json file?

If need be, you can just copy the current version of these files on GitHub and paste them in your local branch to revert the changes :)

**Comment by Ekikereabasi-Nk** [comment]
Thanks for the feedback @andrewtavis

**Review by Ekikereabasi-Nk — COMMENTED** [review]
Hi @andrewtavis I have removed the changes to the Urdu folder that were added from my other pull request. Please let me know if you need me to make any other changes or if you have any questions about this. Thanks

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis it there a problem with this pull request? I will like to know where the problem is, so I can fix it. Thank you

**Comment by andrewtavis** [comment]
Nothing wrong that I can report, @Ekikereabasi-Nk :) I still just need some time to check it as it's a bit more involved. I'll let you know!

**Review by andrewtavis — APPROVED** [review]
The changes to this query get it to where it needs to be @Ekikereabasi-Nk :) Big thing to remember in all of this is that for every form we see on Wikidata, we need to account for all of the properties that make up that form. Then at the end we get an individual row for each form rather than duplicates 😊

Thanks so much for the work here!

**Comment by Ekikereabasi-Nk** [comment]
Alright @andrewtavis I will take note in my next queries and commit. Thank you

**Pull request merged**
