### PR TITLE
complete workflow to check sparql queries

### LINKED ISSUE #339: Add workflow to check queries
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would create a new workflow in [.github/workflows](https://github.com/scribe-org/Scribe-Data/tree/main/.github/workflows) called `check_query_identifiers.yaml` that would call a Python script that would check all queries within the `language_data_extraction` directory to make sure that the identifiers used within them are appropriate. We can put these scripts in a new [.github/workflows](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data) directory called `check`. The scripts would be:

- `/src/scribe_data/check/check_query_identifiers.py` would check all queries in the `language_data_extraction` directory for two things
    - Is the language within `?lexeme dct:language wd:Q12345` in the query appropriate given the directory that it's in?
    - Given the data type of the query - i.e. nouns, verbs, etc - does the QID for this data type appear in `wikibase:lexicalCategory wd:Q12345`?

Queries that fail these conditions should be added to a list and shown to the user in an output of the script and thus the workflow. Something like:

```bash
There are queries that have incorrect language or data type identifiers.

Queries with incorrect languages QIDs are:
- English/nouns/query_nouns.sparql
- ...

Queries with incorrect data type QIDs are:
- English/nouns/query_nouns.sparql  # i.e. a single file should be able to appear in both
- French/verbs/query_verbs_1.sparql
- ...
```

A code snippet that could help with this comes from #330:

```py
def extract_qid_from_sparql(file_path: Path) -> str:
    """
    Extract the QID from the specified SPARQL file.
    Args:
        file_path (Path): Path to the SPARQL file.
    Returns:
        str | None: The extracted QID or None if not found.
    """
    try:
        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read()
            # Use regex to find the QID (e.g., wd:Q34311)
            match = re.search(r"wd:Q\d+", content)
            if match:
                return match.group(0).replace("wd:", "")  # Return the found QID
    except Exception as _:
        pass
        # print(f"Error reading {file_path}: {e}")
    return None  # Return None if not found or an error occurs
```

### Contribution

Happy to support, answer questions and review as needed!

CC @DeleMike and @catreedle :)

### PR DESCRIPTION
**Pull request by DeleMike**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Adds steps in workflow file to run `check_query_identifiers.py`

### Related issue

- fixes #339

### CODE REVIEW

**Comment by DeleMike** [comment]
@andrewtavis, I've finally made the workflow file to work! (omg!!)

but how should the expected behaviour be like? For now, it only logs to the console that the files that have QID issues but the workflow does not actually fail so all green checks. 

How do we wanna approach this? Should the workflow fail? is there a way we could notify the PR author that something is wrong?

**Comment by andrewtavis** [comment]
The workflow should fail :) A big thing is that it's also a tool for maintainers to know if things are wrong in a PR, and and a failed workflow says that loud and clear. We were discussing warnings for GitHub actions in another issue, which apparently are a thing, but let's keep it all to if there's a problem fail the workflow.

**Comment by DeleMike** [comment]
Okay, I'll figure this out. Thanks for the update @andrewtavis!

**Comment by DeleMike** [comment]
@andrewtavis I have updated the codebase to cause the workflow to fail once we have invalid queries.

with this:
```python
# Exit with an error code if any incorrect QIDs are found
if incorrect_languages or incorrect_data_types:
    sys.exit(1)
```

I believe with this, all checks are complete

**Comment by andrewtavis** [comment]
Quick note being sent to all the testing PRs, if updates are needed now that #402 has been merged, then it'd be great to get those updates to the branch :) If no updates are needed, then let me know 😊

**Comment by DeleMike** [comment]
> Quick note being sent to all the testing PRs, if updates are needed now that #402 has been merged, then it'd be great to get those updates to the branch :) If no updates are needed, then let me know 😊

checking...

**Comment by DeleMike** [comment]
Hi @andrewtavis I have adjusted this PR to accommodate the changes from #402 and as you can see a workflow is failing. And that is the one to **Check Query Identifiers**. 

For now, these are the files causing the issue:
```
Incorrect Language QIDs found in the following files:
- /home/runner/work/Scribe-Data/Scribe-Data/src/scribe_data/language_data_extraction/Igbo/verbs/query_verbs.sparql
- /home/runner/work/Scribe-Data/Scribe-Data/src/scribe_data/language_data_extraction/Korean/verbs/query_verbs.sparql
- /home/runner/work/Scribe-Data/Scribe-Data/src/scribe_data/language_data_extraction/Korean/postpositions/query_postpositions.sparql
- /home/runner/work/Scribe-Data/Scribe-Data/src/scribe_data/language_data_extraction/Korean/adverbs/query_adverbs.sparql
```

They are failing because they do not exist in the `language_metadata.json`. Do I update the `json` file so that this workflow passes?

**Comment by DeleMike** [comment]
hi @andrewtavis 👋🏾
I have updated the `language_metadata.json` to support the `Korean` and `Igbo` languages.

I also updated the test cases to ensure we expect these languages 

Now all test cases are passing :)

We can say that all QIDs are valid. Specifically, language QIDs and data type QIDs

**Review by andrewtavis — APPROVED** [review]
Really great work here, @DeleMike 😊 Appreciate your dedication to getting these tests up and running! 🚀

**Pull request merged**
