### PR TITLE
Documentation branch

### LINKED ISSUE #210: Render Jupyter notebooks inside the Scribe-Data documentation
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now the Scribe-Data documentation just presents a link to Jupyter notebooks as is seen on [readthedocs.io:scribe_data/wikipedia/gen_autosuggestions.html](https://scribe-data.readthedocs.io/en/latest/scribe_data/wikipedia/gen_autosuggestions.html). There is an option to render Jupyter notebooks in Sphynx documentation. This issue would add this functionality to our docs :)

### Contribution

This would be a great issue for someone to work on! Happy to answer questions, support as needed and review when a PR is up 😊

### PR DESCRIPTION
**Pull request by AnishereMariam**
### Description

* My pull request solved the issue #210. I was able to render the notebook in a toctree.
Although, I have a bit of a challenge. I tried referring to the .ipynb file directly from the src folder, but it kept returning an error. I had to copy the file into the .rst folder for it to work. I am open to suggestions on how to fix that.

*I had other commits on this PR that fixed some minor bugs I encountered while running the docs file. 
I fixed some indentations and code errors that affect the complete display of the Documentation file.

### Testing
-->I tested my changes with the sphinx-build tool and am confident it works.

### Issue fixed
#210 and some minor bugs.

### CODE REVIEW

**Comment by AnishereMariam** [comment]
I test mine with `sphinx-build -t html source build`.
I am unable to use `make html`

**Review by andrewtavis — APPROVED** [review]
Thanks for the info, @AnishereMariam :) I realized that the problem for me was local likely, as I didn't have pandoc installed apparently. I changed one thing to make it so that the notebooks are never ran. This is really awesome 😊 Thanks so much for the great work here! Maybe we can work on some notebook based usage examples at some point :)

**Comment by AnishereMariam** [comment]
I would love to explore this phase more. It exposed me to some valuable learning experiences. I really enjoy working on this project, generally.

**Comment by andrewtavis** [comment]
Really enjoy having you on the project, @AnishereMariam :) You've had some great contributions :)

**Comment by andrewtavis** [comment]
If you have some further suggestions on how to improve the documentation, then please share!

**Pull request merged**
