### PR TITLE
add a Swahili verbs query

### PR DESCRIPTION
**Pull request by LevisNgigi**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for the contributions and separating them out, @LevisNgigi!

**Comment by LevisNgigi** [comment]
You are welcome, I had not separated them at first but I was able to sort them out.Thank you for your prompt response.Will be contributing to more issues. @andrewtavis

**Comment by andrewtavis** [comment]
Looking forward to the further commits! Feel free to check other projects if you don't find something, and more Scribe-Data issues will be made soon :)

**Comment by LevisNgigi** [comment]
Currently going through the android issues.Will also keep an eye for me issues.

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @LevisNgigi! I'll send along some questions to the issue for you :) Great to have this started!

**Comment by LevisNgigi** [comment]
Thank you @andrewtavis . I will be looking forward to answering the questions and providing as much information as needed. Pleasure is mine.

**Pull request merged**
