### PR TITLE
Add GitHub Action to Check for Dead Links in Documentation

### PR DESCRIPTION
**Pull request by Khushalsarode**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description
- Installs the necessary dependencies from requirements.txt
- Runs the Sphinx linkcheck builder to identify broken links.
- The results are displayed, and if broken links are found, the action will fail.

### Related issue
- #419

### CODE REVIEW

**Comment by andrewtavis** [comment]
I wondering why the workflow didn't run on this, @Khushalsarode 🤔

**Comment by Khushalsarode** [comment]
> I wondering why the workflow didn't run on this, @Khushalsarode 🤔

I was thinking the same.

**Comment by andrewtavis** [comment]
Can you take a look at this and edit the on to be like:

```yaml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
```

Then from there we can look into why it's not running :)

**Comment by Khushalsarode** [comment]
Sure

**Comment by Khushalsarode** [comment]
> Can you take a look at this and edit the on to be like:
> 
> ```yaml
> on:
>   push:
>     branches: [main]
>   pull_request:
>     branches: [main]
>     types: [opened, reopened, synchronize]
> ```
> 
> Then from there we can look into why it's not running :)

Thanks for suggestion and help!
I did run but failed build with error and warnings!
can there be problem at docs side?
@andrewtavis

**Comment by andrewtavis** [comment]
Ok so this is generally ok, @Khushalsarode, but then the error output from the check is kind of messy 🤔 Can you see if there's a way to clean it up a bit? Maybe capture the output and return only the broken links? The thing is that it's hard to find them throughout the entire output that also includes the ones that aren't broken.

**Comment by Khushalsarode** [comment]
@andrewtavis is this ok?

**Comment by andrewtavis** [comment]
Ideally at the end of this @Khushalsarode what we'd get is only those items that are broken because of ` Not Found for url`, and then from there the workflow would fail as well. Can you make those adjustments, and maybe we can also do this for the markdown files as well, not just the docs?

**Comment by Khushalsarode** [comment]
@andrewtavis 
- it will show only link broken because of `Not Found for url` and if found it will exit and mark it as fail flow.
OK?

**Comment by Khushalsarode** [comment]
> Ideally at the end of this @Khushalsarode what we'd get is only those items that are broken because of ` Not Found for url`, and then from there the workflow would fail as well. Can you make those adjustments, and maybe we can also do this for the markdown files as well, not just the docs?

if you would like shall I work on workflow for checking markdown files links.

**Comment by andrewtavis** [comment]
Hey @Khushalsarode 👋 I still see the whole error output at [this link](https://github.com/scribe-org/Scribe-Data/actions/runs/11534683017/job/32108975019?pr=433) that includes links that are ok as well as the ones we want to see. Ideally it would only be the broken links and no others so it's easy for us to maintain.

**Comment by Khushalsarode** [comment]
@andrewtavis 
What is get is
- only want output containing broken links and broken due to url not found
- other than this like ok,redirecting should not to be shown as output 
Correct?

**Comment by andrewtavis** [comment]
Exactly, @Khushalsarode :)

**Comment by andrewtavis** [comment]
And something similar for markdown files :)

**Comment by Khushalsarode** [comment]
@andrewtavis 
is it what we expected?

**Comment by andrewtavis** [comment]
Yes this is great, @Khushalsarode :) Do you want to add in a check for the Markdown files as well? There should be a GitHub action that you can use for this 😊

**Comment by Khushalsarode** [comment]
> Yes this is great, @Khushalsarode :) Do you want to add in a check for the Markdown files as well? There should be a GitHub action that you can use for this 😊

@andrewtavis 
Yes! was waiting for your reponse!
do you want me to create new issue for this or continue ?

**Comment by andrewtavis** [comment]
You can continue in here, @Khushalsarode :)

**Comment by Khushalsarode** [comment]
I will do it!

**Comment by Khushalsarode** [comment]
@andrewtavis  
#499 for markdown files link check workflow

**Comment by andrewtavis** [comment]
I'll check these out soon, @Khushalsarode :) Thanks for them!

**Comment by andrewtavis** [comment]
Can you take a quick look at why it's failing now, @Khushalsarode? All I did was remove some comments and now the check isn't being ran properly 🤔

**Comment by andrewtavis** [comment]
An idea on this, @Khushalsarode: Could you maybe make a Python check script that we could also run locally? Bring in all of the URLs that are in the project even and see if the link is valid via Python requests, and then from there we'll do the check for the docs and the markdown in one go? And to boot we could check it locally and not trail and error the PR tests?

What I'm thinking:
- Get all files that are live under `/docs` (not `/src/build`) and `/src`
- Convert the file contents to strings
- Use regex to get all the links
- Use requests to check the response for each of the links
- Update a dictionary with the file path and a link if it's broken
- Display the file path and link to the user if it's a bad response

How does this sound? :)

**Comment by Khushalsarode** [comment]
> An idea on this, @Khushalsarode: Could you maybe make a Python check script that we could also run locally? Bring in all of the URLs that are in the project even and see if the link is valid via Python requests, and then from there we'll do the check for the docs and the markdown in one go? And to boot we could check it locally and not trail and error the PR tests?
> 
> What I'm thinking:
> 
> * Get all files that are live under `/docs` (not `/src/build`) and `/src`
> * Convert the file contents to strings
> * Use regex to get all the links
> * Use requests to check the response for each of the links
> * Update a dictionary with the file path and a link if it's broken
> * Display the file path and link to the user if it's a bad response
> 
> How does this sound? :)

i will check this one also and will work on your suggestion too!

**Comment by Khushalsarode** [comment]
Don't know what happen to flow suddenly it was running file and script is same but now it's throwing error.
I will work again on this one and will do the one like suggested too

**Comment by Khushalsarode** [comment]
> An idea on this, @Khushalsarode: Could you maybe make a Python check script that we could also run locally? Bring in all of the URLs that are in the project even and see if the link is valid via Python requests, and then from there we'll do the check for the docs and the markdown in one go? And to boot we could check it locally and not trail and error the PR tests?
> 
> What I'm thinking:
> 
> * Get all files that are live under `/docs` (not `/src/build`) and `/src`
> * Convert the file contents to strings
> * Use regex to get all the links
> * Use requests to check the response for each of the links
> * Update a dictionary with the file path and a link if it's broken
> * Display the file path and link to the user if it's a bad response
> 
> How does this sound? :)

Sure @andrewtavis that's also an good valid approach compared workflow!
I will make sure to address this issue soon!
Thanks you!
Also I will try to figure out why this flow is going Rouge to us! 😅🤣

**Comment by andrewtavis** [comment]
Ultimately once this is done, we'll just run the workflow as the others are ran, @Khushalsarode, so it won't be as much of a problem :)

**Comment by Khushalsarode** [comment]
@andrewtavis no issue leave this to me! I have got clearly how we are planning to implement this.

**Comment by andrewtavis** [comment]
Note @Khushalsarode that there was a typo: we don't want urls in `/docs/build` included :) I'd written `/src/build`.

**Comment by Khushalsarode** [comment]
> Note @Khushalsarode that there was a typo: we don't want urls in `/docs/build` included :) I'd written `/src/build`.

ok, we want to check all the links under src/ and docs/ folder? correct?
@andrewtavis

**Comment by andrewtavis** [comment]
Yes, except not under `/docs/build` :)

**Comment by andrewtavis** [comment]
Hey @Khushalsarode 👋 In 2bc53e8 I added a pre-commit hook to check the markdown links. I think that this should be good for the discussed functionality. Appreciate you talking through the potential process with me!

**Pull request closed without merging**
