### PR TITLE
Update query_verbs.sparql

### PR DESCRIPTION
**Pull request by Otom-obhazi**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @Otom-obhazi 👋 For this and your other PR, could you please remove all inline comments that are saying what the identifiers are. These add to query length and processing time. If you use VS Code, there's an extension mentioned in the contributing guide that will tell you what the QIDs are on hover. I'll get to the review of both once these changes go through :) Thank you!

**Comment by andrewtavis** [comment]
This query also returns no results for any of the forms. Can you please reference the new [SPARQL query writing docs](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/wikidata/SPARQL_QUERY_WRITING.md) and make the needed changes to get all the forms? Thank you :)

**Comment by Otom-obhazi** [comment]
@andrewtavis sorry for the mistake, ill do that

**Review by andrewtavis — APPROVED** [review]
Looks like none of these forms have data, @Otom-obhazi, so I removed them :)

**Pull request merged**
