### PR TITLE
Polish queries

### PR DESCRIPTION
**Pull request by Nowshin1077**
Added adjective, adverb and preposition queries

### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

- #233

### CODE REVIEW

**Comment by andrewtavis** [comment]
Can you add the line to get just the lexeme ID instead of the full lexeme URI to these queries, @Nowshin1077? You can see it in the other queries. And would you be able to remove all inline comments. The queries are simple enough that the query doctoring at the top should handle this :)

**Comment by andrewtavis** [comment]
Could you add optional selections of singular and plural forms to this query, @Nowshin1077? :)

**Comment by Nowshin1077** [comment]
@andrewtavis Sure, I am working on it 😊

**Review by andrewtavis — APPROVED** [review]
Will bring this in and we can work further on this in a future issue, @Nowshin1077 :) Trying to clear the PRs and current issues 😊

**Comment by Nowshin1077** [comment]
Sure😊 @andrewtavis

**Pull request merged**
