### PR TITLE
move language_data_extraction under wikidata and lowercase languages

### PR DESCRIPTION
**Pull request by catreedle**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

This PR
-  moves `language_data_extraction` and its contents under [wikidata](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/wikidata)
- changes languages and sub-languages directory name into lowercases
- delete `emoji_keywords` and `generate_emoji_keywords` in language/sub-language directories

### Related issue

- #446

### CODE REVIEW

**Comment by andrewtavis** [comment]
@catreedle, sorry could you address the merge conflicts? Maybe the easiest thing to do would be to redo this PR from main and I'll make sure to bring it in before other PRs?

**Comment by andrewtavis** [comment]
We could even do a call for this at some point to make sure we're in sync?

**Comment by catreedle** [comment]
> @catreedle, sorry could you address the merge conflicts? Maybe the easiest thing to do would be to redo this PR from main and I'll make sure to bring it in before other PRs?

sure, @andrewtavis. on it

**Comment by catreedle** [comment]
> We could even do a call for this at some point to make sure we're in sync?

sure

**Review by andrewtavis — APPROVED** [review]
Not sure about the failed test here as it's passing locally. Let's bring this in so that other people can work from it, @catreedle :) Thanks for this!

**Pull request merged**
