### PR TITLE
Migration - Lowered the languages once in main, and remove from other places, but capitalize for print statements

### PR DESCRIPTION
**Pull request by SethiShreya**
Signed off by Shreya Sethi
shreyasethi47@gmail.com

This PR addresses the issue #446, this PR include:
- lowered the language once in main.py
- remove all the lower functions on the other files
- capitalize for print statements

Tested all the commands on my end, as for total I have tested by first removing all the languages which has sub_languages and everything is working fine.

### CODE REVIEW

**Comment by andrewtavis** [comment]
Are you able to check out the [Pytest issues](https://github.com/scribe-org/Scribe-Data/actions/runs/11617451656/job/32352704178?pr=502) and fix them, @SethiShreya? It may be that the tests need to be rewritten given these changes :)

**Comment by SethiShreya** [comment]
Let me complete it first then i will see that too

**Comment by andrewtavis** [comment]
I'll be cleaning this up to merge, @SethiShreya :)

**Review by andrewtavis — APPROVED** [review]
Really great to have this done, @SethiShreya! 🚀 Really simplifies the code so much 😊 Appreciate your continued suggestions for the project!

**Pull request merged**
