### PR TITLE
added nouns query for latvian language

### PR DESCRIPTION
**Pull request by Khushalsarode**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [X] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description
- added nouns sparql query for latvian langauge by quering against  nouns entity on wikidata.
- query have been tested and executed on wikimedia query editor.

- #413  

@andrewtavis

### CODE REVIEW

**Comment by andrewtavis** [comment]
We can figure out the structure check workflow later, @Khushalsarode. This query currently returns no forms even though there are forms on Latvian nouns available. Can you please reference the new [SPARQL query writing docs](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/wikidata/SPARQL_QUERY_WRITING.md) and make the needed changes to get all the forms? Thank you :)

**Comment by Khushalsarode** [comment]
> We can figure out the structure check workflow later, @Khushalsarode. This query currently returns no forms even though there are forms on Latvian nouns available. Can you please reference the new [SPARQL query writing docs](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/wikidata/SPARQL_QUERY_WRITING.md) and make the needed changes to get all the forms? Thank you :)

Sure!

**Comment by andrewtavis** [comment]
Thank you :)

**Comment by Khushalsarode** [comment]
> We can figure out the structure check workflow later, @Khushalsarode. This query currently returns no forms even though there are forms on Latvian nouns available. Can you please reference the new [SPARQL query writing docs](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/wikidata/SPARQL_QUERY_WRITING.md) and make the needed changes to get all the forms? Thank you :)

updated the query as you asked! please do check, let me know.
@andrewtavis

**Review by andrewtavis — APPROVED** [review]
Still many forms missing, @Khushalsarode, but it was easy enough for me to expand. Please check the final version of the query and use that as a reference for future ones as this is a relatively expansive one for nouns 😊

**Comment by Khushalsarode** [comment]
Thanks!

**Pull request merged**
