### PR TITLE
Create query_adverbs.sparql

### PR DESCRIPTION
**Pull request by Otom-obhazi**
Adverb for Basque

### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
@Otom-obhazi: Are you checking for the forms for the adverbs? Please stop sending pull requests if all you're doing is copying the file and changing the language QID. Yes this is a contribution, but when I'm asking you to work on your current PRs to expand them and then you just send more of the same it's actually disruptive. If you're still unsure of how to check forma and expand them, then ask myself or other contributors.

**Comment by andrewtavis** [comment]
I'm happy to explain, and please let me know that it's still confusing as you have just now rather than continuing to work. I'm wiring out a more detailed explanation now :)

**Comment by Otom-obhazi** [comment]
please can you help me with resources too..
thank you

**Comment by andrewtavis** [comment]
To expand on my explanation that I sent along [here](https://github.com/scribe-org/Scribe-Data/pull/362#issuecomment-2413907369):

- Let's take for example the query for Slovak adjectives [src/scribe_data/language_data_extraction/Slovak/adjecives/query_adjectives.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Slovak/adjecives/query_adjectives.sparql)
- Let's take this query over to query.wikidata.org, but with one edit to return to lexeme URI via `?lexeme`
    - You can see the edited query in the Wikidata Query Service [here](https://w.wiki/BYW8)
    - Note that it includes `?lexeme`
- Run the query and look at the results
- Click on the first result, which will be random, and for me was [wikidata.org/wiki/Lexeme:L238355](https://www.wikidata.org/wiki/Lexeme:L238355)
    - This is the Slovak adjective `slovenský` (the adjective conveniently means Slovak)
    - This is the base adjective, but in Slovak specifically we need to also get forms for the adjectives as they're different based on if the thing is masculine, feminine, etc
    - You can see all of these other forms on the Wikidata page when you scroll down
    - There are forms based on masculine vs. feminine, singular vs. plural and the case that's used
    - These are the forms that we also want to include in our data outputs
- Some of the queries you've sent along don't have forms, so they're fine, but we need to check for the forms before sending them along
- An example of a query for adverbs with tons of forms is [src/scribe_data/language_data_extraction/Estonian/adverbs/query_adverbs_1.sparql](https://github.com/scribe-org/Scribe-Data/blob/c64ea865531ff2de7fe493266d0be0f6be7e5518/src/scribe_data/language_data_extraction/Estonian/adverbs/query_adverbs_1.sparql)
    - Slovak is similar to Estonian in these regards, that there are many forms and they're complex
    - We need to construct forms with an optional selection that includes all the properties that are on the form
    - For the first form above `slovenský` we need to find the Wikidata QIDs for [masculine](https://www.wikidata.org/wiki/Q499327), [nominative case](https://www.wikidata.org/wiki/Q131105), [singular](https://www.wikidata.org/wiki/Q110786), [positive](https://www.wikidata.org/wiki/Q3482678)
    - Then put these within the optional selection to get the form in a way that the returned value is unique

I'll go through now and merge in the PRs that don't have forms. This could be all of them or none of them, but I really would ask that you check for these things beforehand. The Estonian query for instance is dramatically more valuable because it includes all of its forms :)

Let me know if there are further questions! I really appreciate your interest in the project. I hope you understand that I really needed you to pause for a moment so I could explain some things to you so that you can have a better impact on the project 😊

**Comment by andrewtavis** [comment]
> please can you help me with resources too..
> thank you

What do you mean by resources?

**Comment by Otom-obhazi** [comment]
Something that can help me understand better what you want to do.

**Comment by andrewtavis** [comment]
You can check the following:
- [CONTRIBUTING.md](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md)
- Also the [README.md](https://github.com/scribe-org/Scribe-Data/blob/main/README.md)
- And the [documentation](https://scribe-data.readthedocs.io/en/latest/)

**Review by andrewtavis — APPROVED** [review]
Similar for this one, let's be sure to have all directories be lower case except for Languages, @Otom-obhazi :)

**Comment by andrewtavis** [comment]
Thanks for the help!

**Comment by Otom-obhazi** [comment]
something like this
https://github.com/scribe-org/Scribe-Data/pull/381

replying to :

To expand on my explanation that I sent along here
<https://github.com/scribe-org/Scribe-Data/pull/362#issuecomment-2413907369>
:

   - Let's take for example the query for Slovak adjectives
   src/scribe_data/language_data_extraction/Slovak/adjecives/query_adjectives.sparql
   <https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Slovak/adjecives/query_adjectives.sparql>
   - Let's take this query over to query.wikidata.org, but with one edit to
   return to lexeme URI via ?lexeme
      - You can see the edited query in the Wikidata Query Service here
      <https://w.wiki/BYW8>
      - Note that it includes ?lexeme
   - Run the query and look at the results
   - Click on the first result, which will be random, and for me was
   wikidata.org/wiki/Lexeme:L238355
   <https://www.wikidata.org/wiki/Lexeme:L238355>
      - This is the Slovak adjective slovenský (the adjective conveniently
      means Slovak)
      - This is the base adjective, but in Slovak specifically we need to
      also get forms for the adjectives as they're different based on if the
      thing is masculine, feminine, etc
      - You can see all of these other forms on the Wikidata page when you
      scroll down
      - There are forms based on masculine vs. feminine, singular vs.
      plural and the case that's used
      - These are the forms that we also want to include in our data outputs
   - Some of the queries you've sent along don't have forms, so they're
   fine, but we need to check for the forms before sending them along
   - An example of a query for adverbs with tons of forms is
   src/scribe_data/language_data_extraction/Estonian/adverbs/query_adverbs_1.sparql
   <https://github.com/scribe-org/Scribe-Data/blob/c64ea865531ff2de7fe493266d0be0f6be7e5518/src/scribe_data/language_data_extraction/Estonian/adverbs/query_adverbs_1.sparql>
      - Slovak is similar to Estonian in these regards, that there are many
      forms and they're complex
      - We need to construct forms with an optional selection that includes
      all the properties that are on the form
      - For the first form above slovenský we need to find the Wikidata
      QIDs for masculine <https://www.wikidata.org/wiki/Q499327>, nominative
      case <https://www.wikidata.org/wiki/Q131105>, singular
      <https://www.wikidata.org/wiki/Q110786>, positive
      <https://www.wikidata.org/wiki/Q3482678>
      - Then put these within the optional selection to get the form in a
      way that the returned value is unique

I'll go through now and merge in the PRs that don't have forms. This could
be all of them or none of them, but I really would ask that you check for
these things beforehand. The Estonian query for instance is dramatically
more valuable because it includes all of its forms :)

Let me know if there are further questions! I really appreciate your
interest in the project. I hope you understand that I really needed you to
pause for a moment so I could explain some things to you so that you can
have a better impact on the project 😊

**Comment by Otom-obhazi** [comment]
or this >>>>
https://github.com/Otom-obhazi/Scribe-Data/commit/4801aedc27aa28d69d089b2cd2249c4880051f21

**Pull request merged**
