### PR TITLE
Expand Norwegian/Bokmal verb query

### PR DESCRIPTION
**Pull request by VNW22**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description
This pull request expands bokmal verbs query, and have been tested.

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
Can you handle the merge conflict here, @VNW22?

**Comment by VNW22** [comment]
@andrewtavis when adding the QIDs to the lexeme_form_metadata, is there a format i should follow?

**Comment by VNW22** [comment]
Hey @andrewtavis can you help me understand what i need to fix here?
Data/src/scribe_data/language_data_extraction/Norwegian/Bokmål/verbs/query_verbs_1.sparql:
  - masculineFeminineSingularIndefinitePastParticiple : QIDs Q110786 , Q12717679 , Q1775415 , Q499327  not included in metadata
  - SingularneuterIndefinitePastParticiple : QIDs Q110786 , Q12717679 , Q1775461  not included in metadata
  - singularDefinitePastParticiple : QIDs Q110786 , Q12717679  not included in metadata
  - pluralPastParticiple : QID Q12717679  not included in metadata
  - 
Data/src/scribe_data/language_data_extraction/Norwegian/Bokmål/verbs/query_verbs.sparql:
  - presentPerfect : perfectPresentPerfectPerfectPresentPerfect
  - infinitiveActive : QID Q179230  not included in metadata
  - presentActive : QID Q192613  not included in metadata
  - infinitivePassive : QID Q179230  not included in metadata
  - presentPassive : QID Q192613  not included in metadata
  - activePresent : QID Q192613  not included in metadata

**Comment by andrewtavis** [comment]
Sorry I just improved the error output of this, @VNW22 :) You need to add the form to `lexeme_form_metadata.json` in an appropriate place so that we can check if the label is appropriate. `perfectPresentPerfectPerfectPresentPerfect` looks like a bug though 🤔 Do you want to look into this, or should I try to support a bit more?

**Comment by VNW22** [comment]
> Sorry I just improved the error output of this, @VNW22 :) You need to add the form to `lexeme_form_metadata.json` in an appropriate place so that we can check if the label is appropriate. `perfectPresentPerfectPerfectPresentPerfect` looks like a bug though 🤔 Do you want to look into this, or should I try to support a bit more?

sorry, just seeing this now,
I was trying to do so but some forms are alredy in the lexeme_form_metadata.json like masculine, feminine and ost of them. So i was kinda unsure of whta to do next.
I will look into the perfectPresentPerfectPerfectPresentPerfect bug :)

**Comment by andrewtavis** [comment]
This should be figured out if you pull from main, @VNW22. Big thing is that you should format your query a bit, so please put a period before each `.` and `;` and run the check again :) Might be good if there was a specific check for this that would suggest that someone formats the query if it's found that there are non whitespace characters before periods and semicolons.

**Comment by VNW22** [comment]
Got it, thanks! . A specific check for this would definitely be helpful to catch these formatting issues, I can look into it.

**Comment by andrewtavis** [comment]
Would be really great, @VNW22! You can do a regex check for something like `\s+[.;]`, i.e. any number of non space characters followed by period and semicolon. From there have the message added to the error output be that the form needs to be formatted and say that spaces and semicolons need spaces before them. This isn't necessary for the query, but it is coding standard for SPARQL :)

**Comment by andrewtavis** [comment]
So rather than `Invalid query formatting found` for these ones add something more specific like `Invalid query formatting found - please put spaces before all periods and semicolons` :)

**Comment by VNW22** [comment]
I added the check under def check_query_forms() -> None:
  elif query_form_check_dict[k]["form_rep_match"] is False:
                        incorrect_query_labels.append(
                            (k, "Form and representation labels don't match")
                        )

                    # Additional check for formatting
                    elif re.search(r"\S+[.;]", k):
                        incorrect_query_labels.append(
                            (k, "Invalid query formatting found - please put spaces before all periods and semicolons :)")
                        )
  is this okay?

**Comment by andrewtavis** [comment]
Let's give it a try :) I'll check it all after work, but if that's providing the errors to you then looks good to me 😊

**Comment by VNW22** [comment]
I'm thinking of adding a check that would suggest that someone formats the query if it's found that there are whitespace characters before commas after listing the form QIDs, coz i've realise that was the reason why my check was failing

**Comment by VNW22** [comment]
do i open a PR for this?

**Comment by andrewtavis** [comment]
Yes sure, I'll bring this one in and you can open a new PR for the change to the check 😊

**Review by andrewtavis — APPROVED** [review]
Really great work here, @VNW22! Thanks for fixing all the form names 😊

**Pull request merged**
