### PR TITLE
Main

### PR DESCRIPTION
**Pull request by Nowshin1077**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #302

### CODE REVIEW

**Comment by andrewtavis** [comment]
What do you want to do here, @Nowshin1077? I'm not even really sure if the Bengali adverbs query needs to be expanded 🤔 We could do a minor edit in here though?

**Comment by andrewtavis** [comment]
Really no stress about the merge conflict :)

**Comment by andrewtavis** [comment]
I was actually right in the middle of fixing it 😊

**Comment by Nowshin1077** [comment]
Sorry, I noticed after making a PR  that you already added "Adverbs" query 😬, we can do some minor edits though for other queries. Could you please give me some suggestions if possible. I don't know, I am just feeling lost as I am a noob 😬

**Comment by andrewtavis** [comment]
I was thinking when looking at it that adding in `Bangla` would make sense so it's easier for people to find the queries in the codebase if they're searching for this name of the language. Would you have interest in looking into https://github.com/scribe-org/Scribe-Data/issues/236? I can also help you find another!

**Review by andrewtavis — APPROVED** [review]
A few more tips, @Nowshin1077:
- Don't name your branch `Main`
    - Include the issue number you're working on, so `302-bengali-adverbs`
- Also make a branch for your work so that the any changes that are needed are not committed directly to the main of your fork :)

**Comment by andrewtavis** [comment]
Or how does Greek sound? I could make an issue for that for you? :)

**Comment by andrewtavis** [comment]
I.e. adding the language queries for Greek 😊

**Comment by Nowshin1077** [comment]
Thanks fo the tips! I will keep that on my mind. And yeah `Bangla ` would make more sense. 😊

Let me look into https://github.com/scribe-org/Scribe-Data/issues/236 for now then I can move to queries for Greek. 
What do you say?

**Comment by andrewtavis** [comment]
Sounds perfect :)

**Comment by andrewtavis** [comment]
Feel free to write in there and ask for adverbs and adjectives to get started for simple queries, and then we can move to something more difficult 😊

**Pull request merged**
