### PR TITLE
workflow fix

### PR DESCRIPTION
**Pull request by axif0**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
### Description
Here, `steps.pr_count.outputs.result` gets all the merged PR author. and checks if it is 0 (first or not). if o then it'll show the maintainer checklist.

 

- #300

### CODE REVIEW

**Comment by andrewtavis** [comment]
There seems to be some confusion here, @axif0 :) Big thing we're looking for here is "Is this the first PR from the user?", and if so we want to show all of the checkboxes. If it's not their first PR, then we want to show only the second two. We still want maintainers to check off that the linting changes are good and that the changelog has been updated. I think that [actions/first-interaction](https://github.com/actions/first-interaction) would be the easiest way to do this :)

**Comment by axif0** [comment]
Sorry, I was confused for this line `If it is the first pull request, then we would want the first checkbox to be included, and if not, then the first checkbox should be removed.` previously.  Since `actions/first-interaction` requires either issue-message or pr-message to be set. we can set,

```
 - name: Check if this is the user's first PR
        pr-message: " ...  "
- name: Comment PR (First PR)
        if: steps.first_interaction.outputs.first_pr == 'true'
- name: Comment PR (Not First PR)
        if: steps.first_interaction.outputs.first_pr == 'false'
````
Here, for the first user it gives 2 messages. `Check if this is the user's first PR` along with `Comment PR (First PR)`. are we okay with that?

**Comment by andrewtavis** [comment]
Yes, this sounds great @axif0 :) Let's implement this and then merge it and then you can raise a PR to test if we're not getting the first checkbox anymore :?

**Comment by axif0** [comment]
Hello @andrewtavis, I checked First interaction [pull#3](https://github.com/mahbub570/test/pull/3) and furthermore [pull#4](https://github.com/mahbub570/test/pull/4) works perfectly. I searched for `steps.first_interaction.outputs.first_pr` or similar types of variable that returns if `first_interaction` or not. if it is then I could make one message but sadly I can't find any.

**Comment by andrewtavis** [comment]
This makes sense though, @axif0 :) Thanks much!

**Review by andrewtavis — APPROVED** [review]
Really excited about this, @axif0! Let's give this a shot and then maybe you can update the workflow for the other repos that have it?

**Pull request merged**
