### PR TITLE
Add Scribe-Data Logo into Docs Sidebar and Update Color Scheme

### LINKED ISSUE #90: Add Scribe-Data logo to the documentation sidebar header
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One change for the documentation that would be nice to have that is pretty standard is the logo of Scribe-Data in the top left of the documentation page in the header of the docs sidebar. This would replace the home icon and `Scribe-Data` as text as seen below:

Screenshot_2024-03-05 07 51 40

One thing of note, the sidebar header color is blue, so we need a new color if we put the Scribe-Data logo there. We could for instance change the header color to `#F0F0EB` and the sidebar to `#F6F8FA` with the sidebar text being black instead of white :)

### Contribution

Happy to support with this! This issue is being made for someone who's interested in working on the docs 😊

### PR DESCRIPTION
**Pull request by mhmohona**
### Contributor checklist

- [x] This pull request is on a separate branch and not the main branch

---

### Description

Changes made:
- Added `ScribeDataLogo.png` (logo) to the `_static` folder.
- Updated `conf.py` to include `html_logo` and reference the new logo.
- Introduced `custom.css` with styles for sidebar header color, text color, and logo padding.

Tested locally to ensure that the layout appears correctly and that the logo is properly integrated within the sidebar.

image

### Related issue

- Closes #90

### CODE REVIEW

**Review by andrewtavis — APPROVED** [review]
30969ec did the fixes for the comments as discussed above, @mhmohona 😊 Really great stuff here! Thank you!

**Comment by mhmohona** [comment]
@andrewtavis, so after merging this PR, now I am seeing texts in sidebar becomes white when I hover mouse on them - 
image

But when I am running locally it looks like this - 
image

**Comment by andrewtavis** [comment]
Would make sense to do an issue for this, @mhmohona! Thanks for checking!

**Comment by mhmohona** [comment]
@andrewtavis, instead of issue, I submitted the #100, hopefully which is gonna fix the problem.

**Comment by andrewtavis** [comment]
Thank you! I'll take a look as soon as I can :)

**Pull request merged**
