### PR TITLE
 Estonian verb data query

### PR DESCRIPTION
**Pull request by Ekikereabasi-Nk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This pull request introduces a set of SPARQL queries that retrieve various Estonian verb forms

I tested the queries in the Wikidata query service

- #227

### CODE REVIEW

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis i done with the verb queries. It much. I"m done too with the emoji_keyword_generation, only had errors when trying to test of it. I will raise a PR soon

**Comment by andrewtavis** [comment]
The queries are coming out a lot nicer, @Ekikereabasi-Nk :) One thing to note is that we really want one row per result. I think that we need so many files in this case because we're getting lots of results duplicated. There should also be no need for `SELECT DISTINCT` in any of these. Can you go back through and add in indicative and conditional to the queries for present tense and try to put singular and plural into one file? Once that's done and you're getting one row per Wikidata item, you can do the same for other cases?

**Comment by Ekikereabasi-Nk** [comment]
Alright @andrewtavis will do so. Thank for the feedback

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis, I need your assistance. I need a clearer picture to understand "_One thing to note is that we really want one row per result_". While learning I came across the SAMPLE keyword commonly used in queries where there may be multiple results for a variable, and you want to reduce those results to one (it fit into the purpose of one row per result and avoid duplicate). But the downside of SAMPLE is selects only one value from the set of possible values, especially in the case of Estonian verb that has multiple valid forms. Should I use it or stick to other keyword like GROUP BY(which has complexity and query error "Unknown error: java.lang.StackOverflowError" . Thank you

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I done with the verbs changes. Can I also be assign to python based issues, I'm open to joining a team working on an issue. Thank you

**Comment by andrewtavis** [comment]
There's been a lot of progress here, @Ekikereabasi-Nk :) Big thing is that we need to make sure that we have all of the properties on each of the forms, and also that we're getting all of the forms. I'm not seeing third person forms, for instance. Do you want to take a further look into this?

**Comment by Ekikereabasi-Nk** [comment]
Aright @andrewtavis  I will look at it. Thanks for the feedback

**Comment by andrewtavis** [comment]
Feel free to work on the Python for #359 before you jump back over here, @Ekikereabasi-Nk. I know that you want to do Python, so as you wish, but you can take a break from this for now :)

**Review by andrewtavis — APPROVED** [review]
I'll bring this in and make the needed edits, @Ekikereabasi-Nk :) Thanks for the contribution!

**Pull request merged**
