### PR TITLE
Implement pathlib into the update_data.py file

### PR DESCRIPTION
**Pull request by Jk40git**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

--- Expand Scribe-Data paths to allow for Windows commands #125

### Description
Implement pathlib for the paths to be accurately accessed . Don't know if the pathlib was well adopted. Sure there will be some changes to make

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
Ok, @Jk40git :) I've merged in the other PRs for the docs and removed the changes from this PR. There's still lots to do here though. I can help with this, but we're looking to replace all instances where there's a path with a `/` defined via a string with a `Path` object. Let me know if you'd like to work on this a bit more!

**Comment by Jk40git** [comment]
Okay Thanks @andrewtavis I will review my suggestion

**Comment by andrewtavis** [comment]
Should be the Scribe-Data path, @Jk40git :) Feel free to do what you can and @axif0 can also help with the issue 😊

**Comment by andrewtavis** [comment]
Hey @Jk40git 👋 I'm in the midst of doing some fixes for this and will go ahead and take care of it myself. Thanks so much for the efforts in fixing this!

Hope you're well :)

**Comment by Jk40git** [comment]
> Hey @Jk40git 👋 I'm in the midst of doing some fixes for this and will go ahead and take care of it myself. Thanks so much for the efforts in fixing this!
> 
> Hope you're well :)

All right. I am good, been busy those days that's why.

**Pull request closed without merging**
