### PR TITLE
Expand Estonian data queries-Verbs

### PR DESCRIPTION
**Pull request by Ekikereabasi-Nk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This pull request updates the SPARQL queries to ensure comprehensive retrieval of all grammatical features associated with Estonian data queries #227 

### Purpose of the Update

This update provides:
- **Comprehensive grammatical feature coverage**: The updated query now includes all forms, moods, and tenses relevant to Estonian language, ensuring that no important grammatical features are missed.
- **Optimized query structure**: The pull request ensures that the query efficiently retrieves all necessary forms and their grammatical features in a single execution.

### Testing

The SPARQL queries have been tested on the **Wikidata Query Service** to ensure accurate retrieval and performance. 

### Related issue

- #227

### CODE REVIEW

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I'm through with the Estonian adjective, next adverb

**Comment by andrewtavis** [comment]
@Ekikereabasi-Nk: Give me a moment to do a quick edit of this and send along updated queries. This will give you an idea of how to write further ones :)

The big thing, we don't just want one property being returned as the goal is combinations of properties to get exact forms. As what I did for Polish nouns: https://github.com/scribe-org/Scribe-Data/pull/253/files. I'll do these two and then you can look into other queries after 😊

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @Ekikereabasi-Nk! I'll write in the issue about the work that needs to be done for the verbs query 😊 Great progress here!

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I have studied the  SPARQL query from the Polish noun. I have understood what is needed, I'm open to work on any issue concerning the verb query. I'm learning a lot. Thank you.

**Comment by andrewtavis** [comment]
Glad to hear, @Ekikereabasi-Nk! This is pretty tough querying here :) Check out the forms that are already being returned by the verbs query and follow the sections I put out. You'll be fine from there 😊

**Pull request merged**
