### PR TITLE
Fix/sphinx docs build issue

### PR DESCRIPTION
**Pull request by OmarAI2003**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

**Summary of Changes:**
- Commented out the deprecated call to `get_html_theme_path()` in the `conf.py` file to resolve Sphinx build issues.
- Fixed the import error in `process_wiki.py` by removing the outdated reference to `get_language_words_to_remove` and `get_language_words_to_ignore`. 

**Details:**
- Ensured compatibility with Sphinx v7.4.7 by removing deprecated and incompatible code.
- Adjusted the documentation build process to successfully generate the HTML output without significant warnings or errors.
- Fixed issues related to autosummary generation and resolved warnings related to module imports.

**Testing:**
- The build was tested using the powershell command `sphinx-build -b html docs/source/ build/`, resulting in a successful build with no warnings. 

Let me Know your thoughts
@Khushalsarode, @AnishereMariam 

### Related issue

- #382

### CODE REVIEW

**Review by mhmohona — APPROVED** [review]
Doc is now successfully building. Great work @OmarAI2003! ✨

**Comment by OmarAI2003** [comment]
With this last commit, the docs now build for `phinx-autobuild` as well. However, with `phinx-autobuild`, we need to download some additional modules. @andrewtavis Do you want me to update this in `requirements.txt`, or is `phinx-build` sufficient?

**Comment by OmarAI2003** [comment]
Thanks, @Khushalsarode! This is indeed a correct and valid edit for autobuild, and I've included it in a later commit.

**Comment by andrewtavis** [comment]
Let's see if the current one deploys to Read the Docs. If yes, then no stress 😊 If no, then we can revisit it.

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @OmarAI2003! Let's see how this works :)

**Pull request merged**
