### PR TITLE
Russian adjectives and their common forms

### PR DESCRIPTION
**Pull request by OmarAI2003**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

This PR adds a SPARQL file to extract Russian adjectives. Currently, the Russian directory supports extracting nouns, verbs, adverbs, prepositions, emoji_keywords and now and adjectives.

### CODE REVIEW

**Comment by OmarAI2003** [comment]
I made sure to incorporate the feedback you provided in the last PR.let me know if there's anything that needs improvement.

**Comment by andrewtavis** [comment]
There still seem to be a lot of forms that are not included here, @OmarAI2003. Do you want to add them in, or should I look into it?

**Comment by OmarAI2003** [comment]
No, I can add them, but how many more forms do you think this file can accommodate?

**Comment by andrewtavis** [comment]
We can split the file if need be later, @OmarAI2003. Thanks!

**Review by andrewtavis — APPROVED** [review]
We're getting two entries per adjective, but this is fine for now, @OmarAI2003 :) Hopefully we'll write a test at some point that will help us derive what's up here 😊

**Pull request merged**
