### PR TITLE
Fix version comparison bug in get_version_message() due to prefix inconsistencies

### PR DESCRIPTION
**Pull request by harikrishnatp**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

When you run the command scribe-data -v, even if you have the latest version, it incorrectly reports that an update is available. This issue arises due to mismatched values fetched from get_local_version and get_latest_version. The fix involves stripping unnecessary values and comparing only the relevant ones. Additionally, the command to update scribe-data was incorrect and has been corrected.

For testing, I added cases where the local and latest versions are either unknown or different.

### Related issue

- #534

### CODE REVIEW

**Comment by andrewtavis** [comment]
Looks like the file changes for #533 were also included in here, @harikrishnatp :) Just a quick note that we should try to avoid this in the future 😊

**Comment by andrewtavis** [comment]
I made a quick change so that we have `vX.Y.Z` in the tests just to make sure that there's no expectation that these will be maintained and updated as we have upgrades :)

**Review by andrewtavis — APPROVED** [review]
All's wonderful here, @harikrishnatp :) Thank you so much as well for writing the tests! Really appreciate you taking this on and delivering a sustainable solution 😊

**Comment by harikrishnatp** [comment]
Thank you for the kind words and the feedback! I'll be more careful about keeping file changes isolated to their respective PRs! 😄

**Pull request merged**
