### PR TITLE
Fix paths in test_check_query.py Windows compatible

### PR DESCRIPTION
**Pull request by axif0**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
Added a function `normalize_path` . Here it takes a file system path as an input and returns a "normalized" version of that path.
image

### Related issue

- #197

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @axif0 👋 Generally is looking good and I really like the inclusion of marks! Thanks for helping to organize the code :)

Would it be possible to leverage [pathlib](https://docs.python.org/3/library/pathlib.html) for this instead of os. In this way it'd be consistent with the rest of the project :)

**Comment by axif0** [comment]
@andrewtavis thank you so much. pathlib is more realistic to use here. 

@mhmohona In my windows environment, I got no error in testing, for double checking can you please verify it by running the wikidata test ?

**Comment by andrewtavis** [comment]
Thanks so much for the quick fixes here, @axif0! :)

**Review by andrewtavis — APPROVED** [review]
Thanks for the quick reaction to the comments, @axif0! @mhmohona, do let us know if you're seeing anything that needs to be done about the recent commits. For now we're good to merge 😊

**Comment by mhmohona** [comment]
> Thanks for the quick reaction to the comments, @axif0! @mhmohona, do let us know if you're seeing anything that needs to be done about the recent commits. For now we're good to merge 😊

@andrewtavis I just checked. It seems things are working fine, without any error on Windows. ✨ 

and @axif0, good work. 👏🏾

**Pull request merged**
