### PR TITLE
Create prepositions.sparql

### PR DESCRIPTION
**Pull request by Otom-obhazi**
### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by Otom-obhazi** [comment]
@andrewtavis  i don't know how to check and correct this error, is there any thing you have to point me to that direction.

**Comment by OmarAI2003** [comment]
Hi @Otom-obhazi I hope you are doing well. To make sure your queries are in good shape, you should run the scripts for checking queries like:
`py C:\Users\A\Desktop\Scribe-Data\src\scribe_data\check\check_query_forms.py` and 
`py C:\Users\A\Desktop\Scribe-Data\src\scribe_data\check\check_query_forms.py`

**Comment by andrewtavis** [comment]
Ok, sorry for the spam of commits. Seems like something switched in how the macOS environment is set up, and we don't need to install `pkg-config` directly anymore (doing so causes conflicts).

**Review by andrewtavis — APPROVED** [review]
Thanks for sending this along, @Otom-obhazi :) Big thing that caused the run errors: Please make sure to put all queries in a directory for the given data type. This query needed to be in a `prepositions` directory to have passing tests.

**Pull request merged**
