### PR TITLE
Expand Hausa data queries for nouns, proper nouns, and verbs (Issue #116 Solved)

### PR DESCRIPTION
**Pull request by Collins-Webdev**
- Enhanced noun query to include definite and indefinite forms
- Updated proper noun query with definite and vocative forms
- Expanded verb query to cover past simple, present continuous, future tense, and imperative forms
- Added comments and FILTER options for both Latin and Arabic script variants
- Improved overall query structure and readability

### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
Would you be able to solve the merge conflicts here, @Collins-Webdev? :)

**Comment by Collins-Webdev** [comment]
> Would you be able to solve the merge conflicts here, @Collins-Webdev? :)

Sure !

**Comment by Collins-Webdev** [comment]
> Would you be able to solve the merge conflicts here, @Collins-Webdev? :)

**Comment by Collins-Webdev** [comment]
@andrewtavis , conflicts solved ! 😊

**Comment by andrewtavis** [comment]
Hey @Collins-Webdev 👋 Let me handle the rest of this one :) There's a bug in the form check that I'd like to figure out, and this PR is an easy way to test it 😊

**Comment by Collins-Webdev** [comment]
Hey @andrewtavis  👋,

Got it! Thanks for taking care of it 😊. Let me know if you need any further help or testing on my end.

**Review by andrewtavis — APPROVED** [review]
As far as the Hausa queries are concerned, @Collins-Webdev, there's no data being returned for many of the added forms. Let's only add forms in if there is data, as without that we won't exactly no know the Wikidata editors will model the information.

Thanks for this!

**Comment by Collins-Webdev** [comment]
Thanks for merging the PR and helping with the conflict @andrewtavis 🙏🏽.
 Got it on the forms – makes sense not to add them without data. I’ll keep that in mind going forward. 
 Appreciate it 🙏🏽!

**Pull request merged**
