### PR TITLE
Convert camel case to snake case

### PR DESCRIPTION
**Pull request by OmarAI2003**
- Added camel_to_snake function to convert camelCase keys and column headers to snake_case for consistency
- Updated key and column name handling in convert_to_csv_or_tsv and convert_to_json functions

### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description
This PR refactors the Scribe-Data export functionality to ensure consistency in key naming conventions by converting all camelCase JSON keys, CSV/TSV column headers, and SQLite columns to snake_case. This change improves alignment with common conventions for JSON and database formatting.
### Changes Made
- Introduced a `camel_to_snake` helper function to convert camelCase strings to snake_case.
- Updated the `convert_to_json` function to apply the new naming convention to JSON keys.
- Modified the `convert_to_csv_or_tsv` function to apply snake_case conversion to column headers in CSV/TSV exports.
- Converted column names in the `create_table` function to snake_case when creating SQLite tables.

### Related issue

- #312

### CODE REVIEW

**Comment by OmarAI2003** [comment]
Should I close this now?

**Comment by andrewtavis** [comment]
I still need to review and merge it into the project, @OmarAI2003  :)

**Comment by andrewtavis** [comment]
Something that came up in the last sync for this @OmarAI2003 was that the general thought is that some users will want camelCase as well, and that that might be a better default as the data here is more for apps rather than analysis. Could we switch this over to an argument for get and convert whereby the conversion happens only if someone passes `--identifier-case snake`, where the default would be `camel` that they wouldn't need to pass an arg for?

**Comment by OmarAI2003** [comment]
- I added the `--identifier-case` argument to the `convert` command, with "camel" as the default for compatibility with applications.
 - Updated the documentation to include the new `identifier-case` option.

**Review by andrewtavis — APPROVED** [review]
Really some great work here, @OmarAI2003 😊 Thanks so much for the fix post the discussion in the sync! Sorry that the directions weren't as clear from the start, but also great that we have this better solution.

**Pull request merged**
