### PR TITLE
Updated the Yoruba and Japanese language queries

### PR DESCRIPTION
**Pull request by AnishereMariam**
## COMMIT 1
As advised, I added my language to the list (Yoruba), and I updated the noun query. 

## COMMIT 2
I worked on the issue #106, Implement Japanese verb queries:
The query returns a blank result due to an error in the code; I fixed it and tried to add the verb conjugate. 
Unfortunately, the first conjugate I added returns a blank result as well.

## TESTING
I tested the queries on the Wikidata Query Service page "https://query.wikidata.org/"

- #ISSUE_NUMBER
#106

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks so much for the contribution, @AnishereMariam! We'll get to the review as soon as we can :)

**Comment by andrewtavis** [comment]
Hey @AnishereMariam 👋 Quick note that we also have #217 for Yoruba that has another interested person. Maybe you can do nouns and they can do verbs? I'll CC you in that issue :)

**Comment by AnishereMariam** [comment]
Splendid, I received the CC. We could come up with something really nice together. Thank you @andrewtavis .

**Comment by andrewtavis** [comment]
Hey @AnishereMariam 👋 Quickly checked this :) There's nothing coming back from Japanese singular and the Yoruba nouns file is empty. Do you want to bring down my formatting changes and continue to work here? :)

**Comment by AnishereMariam** [comment]
@andrewtavis, I am working with @henrikth93 to complete the Japanese verb query. 

Regarding the Yoruba noun query, I messed up my commit statement. I am really sorry but I fixed it and added a new commit to the PR. 

Also, I pulled your formatting. Thank you

**Review by andrewtavis — APPROVED** [review]
Thanks so much for the initial work here, @AnishereMariam, and sorry that the review took a little bit. Lots to do right now 😊

Looking forward to the next PR! 🚀

**Pull request merged**
