### PR TITLE
Adverb estonian query

### PR DESCRIPTION
**Pull request by Ekikereabasi-Nk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This pull request enhances the SPARQL queries to comprehensively retrieve the grammatical forms of Estonian adverbs from Wikidata. The queries are structured to extract both singular and plural forms, incorporating various grammatical features case such as nominative, genitive, partitive, illative, inessive, elative, allative, adessive, ablative, translative, essive, abessive, and comitative cases.

The singular forms are addressed in Part 1, ensuring all relevant grammatical features are included. Part 2 focuses on retrieving the plural forms with similar grammatical feature coverage. 

### Testing 

The queries were tested on the **Wikidata Query Service**.

- #ISSUE_NUMBER
- #227

### CODE REVIEW

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I'm done with with the Estonian adverb query. Can I still work on the verb query to make is better? But I will focus next on Emoji keywords

**Comment by andrewtavis** [comment]
Yes you can look into verbs as well, @Ekikereabasi-Nk :)

**Comment by andrewtavis** [comment]
Quick feedback, @Ekikereabasi-Nk: Let's please lower case directories, which is standard in Python, and also we don't need to include the language in the name of the file as is the case for the queries for other languages :)

**Comment by andrewtavis** [comment]
Adding `MARK:` to queries to organize them will also make reviewing them easier in the future :)

**Review by andrewtavis — APPROVED** [review]
Check the new versions for a bit more the style that these should be, @Ekikereabasi-Nk :) Specifically it's good to put them into case based sections with `MARK:` so it's easy to see them in the minimap of VS Code, and we also know if a singular or plural is missing. Your original query didn't include terminative singular, which is all good, but organizing it in the way I have will make this obvious in the future 😊

**Comment by Ekikereabasi-Nk** [comment]
@andrewtavis Thank you for the feedback. Sorry if my not getting right. Also I did pull changes from the main branch before I work on any issue, I follow through the instruction from https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#pull-requests-. When I'm done with my work I stage, commit, rebase (git pull --rebase upstream main) and then push. I usually notice during the rebase process I usually have merge conflict , so I use git rebase --skip. When I tried last time to solve the merge conflict I had issue of other people commit include in my branch which i couldn't reconcile.

**Comment by andrewtavis** [comment]
Hmmm ok. My suggestion would be at the very least to just pull to main before you make your branch and then you'll have the most up to date version as your base code :) 

Thanks for the hard work, @Ekikereabasi-Nk!

**Pull request merged**
