### PR TITLE
Create query_adverbs.sparql

### PR DESCRIPTION
**Pull request by Otom-obhazi**
adverbs for Czech

### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
This query does have forms, @Otom-obhazi. Can you please do the following:

- Remove `DISTINCT`
- Check out the query for [Spanish adverbs](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Spanish/adverbs/query_adverbs.sparql)
- Edit this query to also get comparative and superlative forms

Once that's done we'll be good to merge! Let me know if you need any help :)

**Comment by Otom-obhazi** [comment]
Okay

**Comment by andrewtavis** [comment]
Are you going to continue to work on this one now, @Otom-obhazi? I think if you follow what I have for other queries now it'll go well? Note that we're getting all the forms in one line separated by commas, btw, which will make the queries more readable :)

**Review by andrewtavis — APPROVED** [review]
Thanks much for this, @Otom-obhazi! Clearing the PRs out so it doesn't get too much :)

**Comment by Otom-obhazi** [comment]
> This query does have forms, @Otom-obhazi. Can you please do the following:
> 
> * Remove `DISTINCT`
> * Check out the query for [Spanish adverbs](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Spanish/adverbs/query_adverbs.sparql)
> * Edit this query to also get comparative and superlative forms
> 
> Once that's done we'll be good to merge! Let me know if you need any help :)

is this good 
https://github.com/scribe-org/Scribe-Data/pull/368#issuecomment-2414483798

**Comment by Otom-obhazi** [comment]
https://github.com/scribe-org/Scribe-Data/pull/403

**Pull request merged**
