### PR TITLE
Check select where labels order

### PR DESCRIPTION
**Pull request by OmarAI2003**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

**Added `check_forms_order` Function**  
   - Introduced a new function to validate the order of variables in the SELECT clause (excluding `lexeme` and `lexemeID`) against the order in the WHERE clause for SPARQL query files.
   - Implemented pattern matching to handle cases where variable forms are extracted from the WHERE clause.
   - Includes handling for label services providing additional data, ensuring consistency between SELECT and WHERE clause variable orders.

### Related issue

- #450

### CODE REVIEW

**Comment by OmarAI2003** [comment]
We currently have 11 SPARQL files related to the ordering issue. I'm investigating them now and will make the necessary edits and push the updates here

**Comment by OmarAI2003** [comment]
The new check function really paid off! I was able to clean up several inconsistent queries 🥳 🎉 🥳

**Review by andrewtavis — APPROVED** [review]
Thanks so much for this, @OmarAI2003! This process really has come a long way 😊

**Comment by OmarAI2003** [comment]
> Thanks so much for this, @OmarAI2003! This process really has come a long way 😊

I'm not sure now if the two functions `check_undefined_return_forms` and `check_defined_return_forms(query_text: str)` are needed anymore, as this function does the same thing they do, plus checks for the remaining queries (queries with optional clauses) and also does it in orderwise.

**Comment by andrewtavis** [comment]
CC @axif0: Can you check the above functions and send along a PR to remove them if they're covered by this? :)

**Pull request merged**
