### PR TITLE
fixing IncompleteRead issue

### PR DESCRIPTION
**Pull request by axif0**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
Adding this retry logic, we can handle temporary network issues or server-side problems that cause the IncompleteRead error. The code will automatically retry the request a few times before giving up.

### Related issue

- #219

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @axif0 👋 Can you look into the merge conflicts here? :) One thing as well: I'm a bit confused why this is necessary as we already had something to retry queries, but maybe the old one wasn't working 🤔 You can see the old version [here](https://github.com/scribe-org/Scribe-Data/blob/02c7e1bca7c09649ca63b2b3ea3ba78fda3625f8/src/scribe_data/wikidata/query_data.py#L171). Do you want to fix the conflicts and combine the methods as you see fit?

**Comment by axif0** [comment]
@andrewtavis  While running all language querying verbs and nouns, I got the `IncompleteRead` error specifically. After that I ran again and no error. I thought if the error occurs then try few times to reconnect. Maybe some network connection issue from my end. Sorry if you find it irrelevant.

**Comment by andrewtavis** [comment]
No stress whatsoever, @axif0! It's an interesting idea. I'm just wondering if maybe your incomplete read is a more specific implementation of what I was doing with mine. In that case, maybe you could do a slight edit to combine them? :)

**Comment by andrewtavis** [comment]
Let's not forget this, @axif0 :) Basically your implementation checks for `IncompleteRead`, which is what we get back when maybe we've been rate limited by the Query Service or something similar, and then it runs the queries again a certain number of times?

**Comment by axif0** [comment]
@andrewtavis ya.. Agreed with that. I think updated logic is enough. 😅 New implimentation should handle `IncompleteRead` effectively. we can close this PR.

**Comment by andrewtavis** [comment]
I think this is maybe a good way of combining the approaches, @axif0 :) We'll get a more explicit error now, and we'll also let the user know that the query will be retried as your approach did 😊

**Review by andrewtavis — APPROVED** [review]
Thanks as always for the care you're putting into the project, @axif0!

**Pull request merged**
