### PR TITLE
Igbo data queries

### PR DESCRIPTION
**Pull request by Ekikereabasi-Nk**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `pytest` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

This PR expand the Igbo language data extraction capabilities in `src/scribe_data/language_data_extraction/Igbo` by implementing comprehensive SPARQL queries to fetch grammatical features and form from Wikidata.

All SPARQL queries were test and validate on wikidata query service

- #ISSUE_NUMBER
- #399

### CODE REVIEW

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I done with all the Igbo data queries except for the verb. Please do review to let me know if I'm on track. Also I finish up with the Estonian verb and Polish data queries. Thank you

**Comment by Ekikereabasi-Nk** [comment]
Hi @KesharwaniArpita Please can you guide me on how to troubleshoot this fail check `Check Project Structure / structure-check (pull_request)` . I have tried to troubleshoot it, but its not working. Thank you

**Comment by KesharwaniArpita** [comment]
Hi @Ekikereabasi-Nk Can you show me the error you are getting? I am also having little issues with the `Check Project Structure / structure-check`.

**Comment by Ekikereabasi-Nk** [comment]
@KesharwaniArpita These are the error `Run python check_project_structure.py
Errors found:
 - Unexpected file in Igbo/None/nouns: noun_query_2.sparql
 - Unexpected file in Igbo/None/nouns: noun_query_1.sparql
 - Unexpected file in Igbo/None/adverbs: adverb_query.sparql
 - Unexpected file in Igbo/None/prepositions: preposition_query.sparql
 - Unexpected file in Igbo/None/adjectives: adjective_query.sparql` . The `check_project_structure.py` script expected files to be located in specific folders but found that some files are misplaced under a directory named `None.` But the `None` file is don't in my local repo or my origin.

**Comment by KesharwaniArpita** [comment]
Hi again, So I was facing this error with my PR too. `check_project_structure.py` was showing that I had some unidentified files by the names `emoji keywords` which was also leading to more PR run fails. After a while I figured it out it was a naming convention error. The file was supposed to be named `emoji_keywords` instead of `emoji keywords`. I just fixed it and now its working fine. 

To the best of my understanding `check_project_structure.py` is designed to validate the directory structure and the contents of the files in the repo, ensuring that all directories and files adhere to the expected organization. 

I think this is the part that is causing the unexpected file errors where the error sub directory is coming out to be `none`:
image

You can also try renaming your files;  like `noun_query_2.sparql` to `query_nouns_2.sparql` and the other files too so that it matches the given convention. 

Hope it helps!! 😸

**Comment by Ekikereabasi-Nk** [comment]
@KesharwaniArpita Thanks a lot I will try it out

**Comment by andrewtavis** [comment]
Checking in here, are we ready for a review, or is there still some work to be done? Thanks for the collaboration, you two!

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I have done some minor update on the query, please take a look. Thank

**Review by andrewtavis — APPROVED** [review]
Thanks for the updates here, @Ekikereabasi-Nk! I think that the amount of data isn't quite enough for us to have a good understanding of how the data will eventually be modeled, so let's keep the queries simple for now and expand them when more forms are available 😊

**Comment by Ekikereabasi-Nk** [comment]
Alright @andrewtavis, thank you.

**Pull request merged**
