### PR TITLE
Estonian verbs branch

### PR DESCRIPTION
**Pull request by Ekikereabasi-Nk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This pull request includes all available **grammatical features** for Estonian verbs. The SPARQL code extracts verb forms with the following grammatical features:

- Supine (Q548470): A non-finite verb form used in certain constructions.
- Inessive case (Q282031): Locative case, indicating position inside something.
- Elative case (Q394253): Case indicating motion out of or away from something.
- Translative case (Q950170): Case indicating a change of state or transformation.
- Abessive case (Q319822): Case indicating absence or without something.
- Present participle (Q10345583): A verb form indicating an ongoing action in the present.
- Past participle (Q1230649): A verb form indicating a completed action in the past.
- Transgressive (Q904896): A form indicating simultaneous action in non-finite constructions.
- Indicative (Q682111): A mood used to state facts or ask questions.
- Present tense (Q192613): Tense used to describe actions happening now or regularly.
- Simple past (Q1392475): Tense used to describe completed actions in the past.
- Conditional (Q625581): Mood expressing hypothetical or non-real actions.
- Imperative (Q22716): Mood used to give commands or make requests.
- Jussive (Q462367): Mood expressing indirect commands or permission.
- Singular (Q110786): Grammatical number indicating a single entity.
- Plural (Q146786): Grammatical number indicating multiple entities.
- First person (Q21714344): Refers to the speaker or speakers (I/we).
- Second person (Q51929049): Refers to the addressee or addressees (you).
- Third person (Q51929074): Refers to other people or things (he/she/they).
- Impersonal verb (Q1509829): Verbs where the agent is unspecified or generic.
- Indirect speech (Q1006348): Verb forms used in indirect reporting of speech.
- Negation (Q1478451): A grammatical feature used to indicate the negation of a verb action.

###Purpose of the Update
This update provides:

- **Comprehensive grammatical feature coverage**: The updated query now includes all forms, moods, and tenses relevant to Estonian verbs, ensuring that no important grammatical features are missed.

- **Optimized query structure**: The pull request ensures that the query efficiently retrieves all necessary verb forms and their grammatical features in a single execution.

- #ISSUE_NUMBER

-   #227

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @Ekikereabasi-Nk 👋 Do you maybe want to move the Estonian verbs over to a new branch that doesn't have all the commits from other people in it? Just make a new branch and copy just the verb changes over? This PR might get a bit messy with conflicts, I worry :)

**Comment by Ekikereabasi-Nk** [comment]
@andrewtavis I have be trying to resolve the issue. I will create a new branch and PR

**Comment by andrewtavis** [comment]
Sounds good, @Ekikereabasi-Nk :) Sometimes it's easier to just do it that way 😊

**Comment by andrewtavis** [comment]
Closing this in favor of #294 :) Thanks for the new PR, @Ekikereabasi-Nk!

**Pull request closed without merging**
