### PR TITLE
Added Finnish verb query. 

### PR DESCRIPTION
**Pull request by Ebeleokolo**
This PR introduces the SPARQL query that expands the Finnish verb query.

The query was tested using the Wikidata query service.

Any feedback or suggestions are greatly appreciated.

### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
Workflow is functioning, @axif0! Thanks for it :)

**Comment by andrewtavis** [comment]
Thanks for this, @Ebeleokolo. One check here, how do you know that these forms are appropriate? When I run the query I don't get any results for many of them 🤔

**Comment by Ebeleokolo** [comment]
Hello @andrewtavis, there isn't much data available in Wikidata for Finnish verbs at the moment. Out of the forms I added in the query, only about 7 return results. I could update the query to only include the forms that currently have data, or we can wait for more Finnish verb data to be added in the future. Please let me know your thoughts on this. Thank you

**Comment by andrewtavis** [comment]
Hey @Ebeleokolo 👋 It might be best for us to only include the forms that return data for now so that we don't use a modeling strategy that might not be used by the editors :) Can you rework it so only the forms that have data are gotten, and we can then revisit this later? Thank you!

**Comment by Ebeleokolo** [comment]
Hello  @andrewtavis, I have removed the forms that don't return data. Kindly check and notify me of any other issues. Thank you.

**Comment by andrewtavis** [comment]
@Ebeleokolo, there are now tons of commits on this PR because of some weird branch merging 🤔 Do you want to open a new PR with the new Finnish verbs query just by itself after pulling from main to your fork/branch?

As it is I wouldn't be able to review this, so would be great if you open a new PR or fix the commits here!

**Comment by andrewtavis** [comment]
Closing this as the work was done in #398. Thanks @Ebeleokolo!

**Pull request closed without merging**
