### PR TITLE
Issue #135: Update docs with file types and directory indicators

### PR DESCRIPTION
**Pull request by lillian-mo**
### Contributor checklist

- [x] This pull request is on [lillian-branch] (https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- #135

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @lillian-mo 👋 One thing to note from our [maintainer checklist](https://github.com/scribe-org/Scribe-Data/pull/185#issuecomment-2295467010) is that it looks like your GitHub email isn't set up properly. Normally the [commits for the PR](https://github.com/scribe-org/Scribe-Data/pull/185/commits) should be authored by the same person and the icons should be the same as well. It looks like your Git `user.name` is set up properly, which indicates that it's likely your email. Can you check that the [email you use for GitHub](https://github.com/settings/emails) is the same as what you get for `git config user.email`. From there we can check if the PR fixes itself, or maybe we can reopen it :)

There's no "problem" with the code as it is, but if I were to merge this then your account wouldn't get the commit credit :)

**Comment by lillian-mo** [comment]
> Hey @lillian-mo 👋 One thing to note from our [maintainer checklist](https://github.com/scribe-org/Scribe-Data/pull/185#issuecomment-2295467010) is that it looks like your GitHub email isn't set up properly. Normally the [commits for the PR](https://github.com/scribe-org/Scribe-Data/pull/185/commits) should be authored by the same person and the icons should be the same as well. It looks like your Git `user.name` is set up properly, which indicates that it's likely your email. Can you check that the [email you use for GitHub](https://github.com/settings/emails) is the same as what you get for `git config user.email`. From there we can check if the PR fixes itself, or maybe we can reopen it :)
> 
> There's no "problem" with the code as it is, but if I were to merge this then your account wouldn't get the commit credit :)

Thanks for letting me know! I've configured my git user.email so that it's my personal email here. Hopefully that works :)

**Comment by andrewtavis** [comment]
Nice! Do you want to reopen the PR regardless? Likely still won't give you the credit as it is :) Is good for us to have you listed as a contributor as well 😊

**Comment by andrewtavis** [comment]
Hope it's ok that I close with the plan of reopening, @lillian-mo! Just go ahead and send along the same code and I'll quickly bring it in :)

**Review by andrewtavis — APPROVED** [review]
Reopening so we can close out the issue :) We do have you set up for future contributions, and maybe you can get the contribution this time 🤞

All looks great, @lillian-mo! Thanks so much for the contribution here :) :)

**Pull request merged**
