### PR TITLE
Hashmap vs if-elif-else

### PR DESCRIPTION
**Pull request by to-sta**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
While procrastinating, I came across some code that used a series of if-elif-else blocks. I realized that these could be optimized by using a dictionary (hashmap), which would likely result in better performance.

I updated the README file to include the command for activating the virtual environment using Windows PowerShell.

### Related issue

- No related issue

### CODE REVIEW

**Comment by andrewtavis** [comment]
CC @wkyoshida 😊😊😊

**Review by andrewtavis — APPROVED** [review]
Thanks for the improvements, @to-sta! Wonderful to have you as a contributor over here 😊🥳

**Comment by andrewtavis** [comment]
I didn't know what I was looking at for a sec when I saw the email alert about the PR 😅 to-sta, Scribe-Data?? 😊

**Comment by to-sta** [comment]
> I didn't know what I was looking at for a sec when I saw the email alert about the PR 😅 to-sta, Scribe-Data?? 😊

I was teaching coding all day yesterday and thought I should also code a bit at the end of the day 😄. 

Our issues at activist.org would have consumed more than half an hour 😅. Here I found something fairly simple 👌🏻

**Pull request merged**
