### PR TITLE
emoji: adding parameter functionality for gen_emoji_autosuggestions()

### PR DESCRIPTION
**Pull request by wkyoshida**
**Description:**
- Added functionality for the `ignore_keywords` parameter of `gen_emoji_autosuggestions()`
- Added functionality for the `num_emojis` parameter of `gen_emoji_autosuggestions()`

**Next Step:**
- Still missing functionality for the last parameter, `verbose` (thinking of getting that in tomorrow)

### CODE REVIEW

**Comment by andrewtavis** [comment]
Will check this when you send along the next commit, @wkyoshida 😊 Thanks as always!

**Comment by wkyoshida** [comment]
Wasn't able to get to `verbose` today unfortunately; apologies. But will still this week, certainly. :grin:

**Comment by andrewtavis** [comment]
No stress! Get to it when you can 😊

**Comment by andrewtavis** [comment]
Output looks great, @wkyoshida! Are we planning on doing the `emojis_per_word` argument in here? I'm also very happy to do that after I merge.

**Comment by wkyoshida** [comment]
@andrewtavis, I got you!
I had already started taking a look into it :wink: Thinking I'll have something tomorrow!

**Comment by andrewtavis** [comment]
Great! Looking forward to it, @wkyoshida! 😊

**Comment by wkyoshida** [comment]
Hey @andrewtavis! Just to quickly let you know - something came up yesterday, apologies. I'll see to get to this soon though :+1:

**Comment by andrewtavis** [comment]
No stress, @wkyoshida! Get to it when you can 😊

**Comment by wkyoshida** [comment]
Hey, @andrewtavis! Dealing with some personal matters _atm_.. Apologies for the slight wait, but I pushed up now the other option :+1:  I went with naming it `num_per_keyword` - if that makes sense. 

Initially, I spent some time thinking through an implementation to always keep the list of emojis per keyword sorted and limited to `num_per_keyword` while they are getting read/processed - perhaps using a heap or something, but I thought it was getting too convoluted for our use case. So, eventually I settled with simply sorting the emojis after they've all been read from the CLDR data and then saving the top 'N', i.e. `num_per_keyword`. Seems to be fine for what we need.

**Comment by andrewtavis** [comment]
Sorry @wkyoshida, have been telling myself to get to this for ages now, but am deep in trying to get an alpha out for the other project I mentioned...

First and foremost, I hope that the personal matters are going better at this point.

The description of the most recent commit makes total sense! I'm very close to getting a landing page up so me and the teammate for the other project can start talking to folks about what we're working on. After that I'll jump back in here and we can work on this some more 😊 Again my apologies that this has been sitting for so long!

Wishing you all the best!

**Comment by wkyoshida** [comment]
Hey @andrewtavis, thank you truly for the sentiment :blush: Things are better now at this point; think I'll be able to be back more :raised_hands: 

And no worries! Excited to eventually see what it is that you've been working on!

**Review by andrewtavis — APPROVED** [review]
Hey @wkyoshida! Sorry for not getting to this for so long 🤦‍♂️ Initial glances months ago looked really great, and all's functioning as expected 😊 I'll run this later on today to update the data files in Scribe-iOS so that we can get started with [Scribe-iOS #51](https://github.com/scribe-org/Scribe-iOS/issues/51) :)

**Pull request merged**
