### PR TITLE
expanded danish queries

### PR DESCRIPTION
**Pull request by Kehindeadebisi**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
This pr focuses on expanding the src/scribe_data/language_data_extraction/Danish files with as much data as possible from Wikidata, building on existing patterns used in other language data extractions.

Data types included are:
Adjectives
Adverbs
Emoji-keywords

I tested the queries in the [Wikidata query service](https://query.wikidata.org/) and ran the py file though did not include the json output as advised

### Related issue

- #342

### CODE REVIEW

**Comment by andrewtavis** [comment]
This generally looks good, @Kehindeadebisi, but can we expand the forms we're getting back for adjectives? See [wikidata.org/wiki/Lexeme:L43599](https://www.wikidata.org/wiki/Lexeme:L43599) and maybe check a few others to see the forms we can get :)

**Comment by Kehindeadebisi** [comment]
> This generally looks good, @Kehindeadebisi, but can we expand the forms we're getting back for adjectives? See [wikidata.org/wiki/Lexeme:L43599](https://www.wikidata.org/wiki/Lexeme:L43599) and maybe check a few others to see the forms we can get :)

[Done](https://github.com/scribe-org/Scribe-Data/pull/349/commits/ec629ec668f7c4168e575d32902e5e6fead5176f) @andrewtavis

**Review by andrewtavis — APPROVED** [review]
Thanks for the work here, @Kehindeadebisi! 😊 One thing to note, when we're expanding queries the goal is a combination of properties such that each form is returned uniquely. It sometimes can be a bit difficult, but it's important to combine the properties and not just have one property per returned column as that means that we get repeat rows :)

**Comment by Kehindeadebisi** [comment]
Noted, thanks for the feedback!

**Pull request merged**
