### PR TITLE
Expanded Malayalam verbs to include other forms on Wikidata

### PR DESCRIPTION
**Pull request by Kehindeadebisi**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
This pull request expands the Malayalam verbs query to include additional forms available on Wikidata, specifically:
- Present infinitive
- Simple present
- Simple past
- Simple future

The updated query was tested on the [Wikidata Query Service UI](https://query.wikidata.org/), and the expected forms were successfully retrieved.
### Related issue
[Expand Malayalam verbs query #231](https://github.com/scribe-org/Scribe-Data/issues/231)

- #ISSUE_NUMBER

### CODE REVIEW

**Comment by andrewtavis** [comment]
All's generally looking ok here, @Kehindeadebisi, but it looks like your email isn't set up right for GitHub. Can you check that what you have for `git config user.email` in the terminal is the same as what you have for the [email you use for GitHub](https://github.com/settings/emails)?

**Comment by andrewtavis** [comment]
We can then maybe close and reopen a new PR, or you could try to recommit to this PR :)

**Comment by andrewtavis** [comment]
All will work, but your GitHub account won't get the commit credit if your email isn't set properly.

**Comment by Kehindeadebisi** [comment]
Thank you so much for the review and for drawing my attention to difference in email @andrewtavis. I have changed the email and amended the commit

**Comment by andrewtavis** [comment]
Looking good now :) I'll try to get to the review tonight 😊

**Comment by Kehindeadebisi** [comment]
> Looking good now :) I'll try to get to the review tonight 😊

thanks!

**Review by andrewtavis — APPROVED** [review]
Thanks for the great contribution and fixing your email so quickly, @Kehindeadebisi! 🚀😊

**Pull request merged**
